version: '3.9'

services:
  test_postgres_db:
    image: postgres:15.5-alpine3.19
    container_name: test_postgres_db
    env_file:
      - .env
    volumes:
      - test_pg_data:/var/lib/postgresql/data

  test_redis:
    image: redis:7.2.3-alpine3.18
    container_name: test_redis
    restart: always
    env_file:
      - .env
    volumes:
      - test_redis_data:/data

  test_auth_api:
    container_name: test_AuthAPI
    command: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9999
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${TEST_POSTGRES_HOST}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_PORT: ${TEST_POSTGRES_PORT}
      REDIS_HOST: ${TEST_REDIS_HOST}
      REDIS_PORT: ${TEST_REDIS_PORT}
    volumes:
      - ./AuthAPI/src:/src
    build:
      context: src
      dockerfile: Dockerfile
    depends_on:
      test_postgres_db:
        condition: service_started
      test_redis:
        condition: service_started
    ports:
      - "9999:9999"

  tests:
    build:
      context: Tests
      dockerfile: dockerfile
    image: async_tests
    env_file:
      - .env
    entrypoint: >
      sh -c "
      pytest functional/src/"

volumes:
  test_pg_data:
  test_redis_data: